### PR TITLE
Using the snap version to download the necessary deb file

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Review by CapeCrusader321 — APPROVED** [review]

**Comment by soumyaDghosh** [comment]
A request to u, please use better commit messages, I also once wrote these kind of messages, but they are not so helpful. Also, ig you're Indian right? Nice to know a snapper like you. 

Madad karenge bro. No chinta.

**Comment by CapeCrusader321** [comment]
Thanks for the suggestion,  a small error its project instead of prohect (typo maybe ?)

**Comment by soumyaDghosh** [comment]
Ohhh right sorry for that

**Comment by CapeCrusader321** [comment]
Yeah AM Indian 🇮🇳

**Comment by soumyaDghosh** [comment]
Check the curtail too. That's not fixed though completely. But error is there. All of your snaps can be optimized well and good.

**Comment by CapeCrusader321** [comment]
> Check the curtail too. That's not fixed though completely. But error is there. All of your snaps can be optimized well and good.

Ok

**Pull request merged**
